const fs = require('fs');
const path = require('path');
const { withDangerousMod } = require('expo/config-plugins');

/**
 * Use OUR debug keystore instead of the one Expo's prebuild ships.
 *
 * Expo templates ship a single shared `debug.keystore`, so every project generated from them
 * has the same SHA-1 fingerprint. Google enforces global uniqueness on
 * (package name + fingerprint) for Android OAuth clients, which means registering
 * `com.chukta.app` against that shared fingerprint fails with:
 *
 *     Ownership verification failed — the Android package name and fingerprint
 *     are already in use
 *
 * ...because somebody else got there first with the same borrowed key.
 *
 * `android/` is regenerated by prebuild, so copying the file in by hand would not survive.
 * This plugin re-copies it on every prebuild.
 *
 * The alias and passwords deliberately match React Native's defaults (`androiddebugkey` /
 * `android`), so the generated Gradle signing config needs no changes.
 *
 * DEBUG ONLY. The release upload key is generated and held by EAS and is never in this repo.
 */
module.exports = function withDebugKeystore(config) {
  return withDangerousMod(config, [
    'android',
    async (cfg) => {
      const source = path.join(cfg.modRequest.projectRoot, 'credentials', 'debug.keystore');
      const target = path.join(cfg.modRequest.platformProjectRoot, 'app', 'debug.keystore');

      if (!fs.existsSync(source)) {
        throw new Error(
          `withDebugKeystore: missing ${source}. Regenerate it — see docs/setup-services.md.`,
        );
      }

      fs.copyFileSync(source, target);
      return cfg;
    },
  ]);
};
