const { withAndroidManifest } = require('expo/config-plugins');

/**
 * Declare what this app is allowed to see, so UPI discovery works on Android 11+.
 *
 * Android 11 made package visibility opt-in. Without a matching `<queries>` entry,
 * `queryIntentActivities` returns an EMPTY LIST rather than an error — every UPI app on the
 * device looks uninstalled, the picker looks broken, and nothing anywhere says why. It is the
 * single most common reason UPI integrations break on modern Android.
 *
 * `android/` is regenerated by prebuild and gitignored, so this cannot live as a hand edit to
 * the manifest; it has to be a plugin that reapplies on every build. Same reasoning as
 * `withDebugKeystore.js`.
 *
 * Scoped to the `upi` scheme deliberately. A bare `<queries><intent>` for ACTION_VIEW would
 * grant visibility of far more than we need, and Play's policy on broad package visibility is
 * strict enough that over-asking is a review risk as well as a privacy one.
 */
const withUpiQueries = (config) =>
  withAndroidManifest(config, (mod) => {
    const manifest = mod.modResults.manifest;

    manifest.queries = manifest.queries ?? [];
    if (manifest.queries.length === 0) manifest.queries.push({});

    const queries = manifest.queries[0];
    queries.intent = queries.intent ?? [];

    const alreadyDeclared = queries.intent.some((intent) =>
      intent?.data?.some((d) => d?.$?.['android:scheme'] === 'upi'),
    );

    if (!alreadyDeclared) {
      queries.intent.push({
        action: [{ $: { 'android:name': 'android.intent.action.VIEW' } }],
        data: [{ $: { 'android:scheme': 'upi' } }],
      });
    }

    return mod;
  });

module.exports = withUpiQueries;
