const { withAndroidManifest } = require('expo/config-plugins');

/**
 * Declare what this app is allowed to see, so UPI discovery works on Android 11+.
 *
 * Android 11 made package visibility opt-in. Without a matching `<queries>` entry,
 * `queryIntentActivities` returns an EMPTY LIST rather than an error — every UPI app on the
 * device looks uninstalled, the picker looks broken, and nothing anywhere says why. It is the
 * single most common reason UPI integrations break on modern Android.
 *
 * `android/` is regenerated by prebuild and gitignored, so this cannot live as a hand edit to
 * the manifest; it has to be a plugin that reapplies on every build. Same reasoning as
 * `withDebugKeystore.js`.
 *
 * Scoped to the `upi` scheme deliberately. A bare `<queries><intent>` for ACTION_VIEW would
 * grant visibility of far more than we need, and Play's policy on broad package visibility is
 * strict enough that over-asking is a review risk as well as a privacy one.
 */
const withUpiQueries = (config) =>
  withAndroidManifest(config, (mod) => {
    const manifest = mod.modResults.manifest;

    manifest.queries = manifest.queries ?? [];
    if (manifest.queries.length === 0) manifest.queries.push({});

    const queries = manifest.queries[0];
    queries.intent = queries.intent ?? [];

    const alreadyDeclared = queries.intent.some((intent) =>
      intent?.data?.some((d) => d?.$?.['android:scheme'] === 'upi'),
    );

    if (!alreadyDeclared) {
      /*
       * TWO entries, and the one with the host is the one that actually works.
       *
       * This declared `scheme="upi"` alone, and on a real phone with Google Pay and PhonePe
       * installed it matched NOTHING — no tiles, and the generic "Open a UPI app" button fell
       * straight through to the QR code. The emulator could never have caught it: it has no UPI
       * apps to be invisible.
       *
       * The reason is that Android matches a `<queries>` declaration against each app's intent
       * filter using ordinary IntentFilter rules. A declaration of `scheme` only describes the
       * Uri `upi:`, which has no authority — and a filter that DECLARES an authority rejects a
       * Uri without one. GPay and PhonePe register `<data android:scheme="upi"
       * android:host="pay"/>`, so they stayed invisible and `queryIntentActivities` returned an
       * empty list with no error to explain it.
       *
       * The inconsistency was already visible in our own code: `UpiModule.kt` probes with
       * `upi://pay?...`, host included. Only the declaration that has to make those apps
       * visible omitted it.
       *
       * The scheme-only entry is kept as well, for an app that registers without an authority —
       * a filter with no authority matches any Uri of that scheme, so it is the host-less apps
       * that need it. Both stay scoped to `upi:`, so this asks for no broader visibility than
       * before; it asks for the RIGHT visibility.
       */
      queries.intent.push({
        action: [{ $: { 'android:name': 'android.intent.action.VIEW' } }],
        data: [{ $: { 'android:scheme': 'upi', 'android:host': 'pay' } }],
      });
      queries.intent.push({
        action: [{ $: { 'android:name': 'android.intent.action.VIEW' } }],
        data: [{ $: { 'android:scheme': 'upi' } }],
      });
    }

    return mod;
  });

module.exports = withUpiQueries;
