const { withDangerousMod } = require('expo/config-plugins');
const fs = require('fs');
const path = require('path');

/**
 * Let Google Sign-In's Swift dependencies build as static libraries.
 *
 * `pod install` fails outright without this:
 *
 *   The Swift pod `AppCheckCore` depends upon `GoogleUtilities` and `RecaptchaInterop`,
 *   which do not define modules.
 *
 * Those two are Objective-C pods that ship no module map, and a Swift pod cannot import an
 * Objective-C pod as a static library unless one is generated. `:modular_headers => true`
 * generates it.
 *
 * Named individually rather than a blanket `use_modular_headers!`: the global form changes
 * header visibility for EVERY pod in the project, which is a large blast radius for a problem
 * with two known causes — and it has a history of breaking React Native's own pods.
 *
 * This has to be a plugin rather than a Podfile edit because `ios/` is gitignored and
 * regenerated by prebuild, exactly like `withDebugKeystore` and `withUpiQueries`. A dangerous
 * mod is the right tool: Expo has no typed modifier for adding a pod, and this runs before
 * `pod install` during prebuild.
 */
const POD_LINES = [
  "  # Added by plugins/withModularHeaders.js — see that file for why these are named",
  "  # individually rather than using a global use_modular_headers!.",
  "  pod 'GoogleUtilities', :modular_headers => true",
  "  pod 'RecaptchaInterop', :modular_headers => true",
  "  pod 'AppCheckCore', :modular_headers => true",
];

const MARKER = 'plugins/withModularHeaders.js';

const withModularHeaders = (config) =>
  withDangerousMod(config, [
    'ios',
    async (mod) => {
      const podfile = path.join(mod.modRequest.platformProjectRoot, 'Podfile');
      const contents = fs.readFileSync(podfile, 'utf8');

      // Prebuild can run repeatedly against an existing ios/ directory.
      if (contents.includes(MARKER)) return mod;

      const anchor = /^(target '.*' do\n)/m;
      if (!anchor.test(contents)) {
        throw new Error(
          'withModularHeaders: could not find the app target in the Podfile. The Expo Podfile ' +
            'template changed — update this plugin rather than letting pod install fail with a ' +
            'message about module maps.',
        );
      }

      fs.writeFileSync(
        podfile,
        contents.replace(anchor, (match) => `${match}${POD_LINES.join('\n')}\n\n`),
      );

      return mod;
    },
  ]);

module.exports = withModularHeaders;
